### PR TITLE
try to fix issue #577

### PR DESCRIPTION
**Pull request by Mark-Fenng**
try to fix issue [#577](https://github.com/rrweb-io/rrweb/issues/577)

### CODE REVIEW

**Comment by Yuyz0112** [comment]
@Mark-Fenng I think the original issue may happen when there is serialization progress in the users' backend that turns undefined to null in JSON.

**Comment by Mark-Fenng** [comment]
That makes sense but the undefined values may also cause unexpected behavior.
image

**Comment by Yuyz0112** [comment]
@Mark-Fenng Yes, but I think we will not get undefined values from JSON-based events.

```
JSON.stringify({ a: 1, b: undefined})
// "{\"a\":1}"
```

And I'm thinking how could we get undefined from TextNode.textContent in runtime?

**Comment by Mark-Fenng** [comment]
Ok, we should rather pay attention to its root cause.

**Pull request closed without merging**
