### PR TITLE
fix media playback bug

### PR DESCRIPTION
**Pull request by bachmanity1**
This fixes media playback issue reported in [#573](https://github.com/rrweb-io/rrweb/issues/573)

### CODE REVIEW

**Comment by bachmanity1** [comment]
@Yuyz0112 can check this out?

**Comment by bachmanity1** [comment]
@eoghanmurray could you review this? @Yuyz0112 seems to be too busy.

**Comment by eoghanmurray** [comment]
I won't have a chance to look at this; not familiar enough with either promises or the video element, sorry!
Is it easy to generate a simple test that fails without this patch?

**Comment by bachmanity1** [comment]
@eoghanmurray set `checkoutEveryNms` to short period(example 5 seconds) and try to record a page that has `HTMLVideoElement`(make sure video is playing), in a replayed page you'll notice that video crashes after full snapshot rebuild. 
Can you tag someone else who is more familiar with `rrweb-snapshot`, maybe @Mark-Fenng can help us?

**Comment by Mark-Fenng** [comment]
I have met this problem several times and please give me some time to verify your solution.

**Comment by Mark-Fenng** [comment]
@bachmanity1  LGTM, thanks!

**Comment by Yuyz0112** [comment]
Thanks for this and the review from @Mark-Fenng 

I can release a new version of rrweb-snapshot tonight.

**Pull request merged**
